/**
 * Physical Speed Editor layout.
 * HID codes come from the publicly documented Speed Editor protocol
 * (Sylvain Munaut / blackmagic-misc).
 */
const SPEED_EDITOR_BUTTONS = [
  {
    id: "smart-insrt",
    cluster: "edit",
    hid: 0x01,
    label: "SMART INSRT",
    secondary: "CLIP",
    variant: "dark",
    factoryName: "Smart Insert",
    factorySecondaryName: "Clip",
    description:
      "Inserts the clip from the source viewer into the timeline at the playhead, and pushes later clips to the right to make room.",
  },
  {
    id: "appnd",
    cluster: "edit",
    hid: 0x02,
    label: "APPND",
    secondary: "CLIP",
    variant: "dark",
    factoryName: "Append",
    factorySecondaryName: "Clip",
    description: "Adds the source clip onto the end of the current timeline.",
  },
  {
    id: "ripl-owr",
    cluster: "edit",
    hid: 0x03,
    label: "RIPL O/WR",
    variant: "dark",
    factoryName: "Ripple Overwrite",
    description:
      "Overwrites the timeline with the source clip and ripples the rest of the timeline so nothing is left as a gap.",
  },
  {
    id: "close-up",
    cluster: "edit",
    hid: 0x04,
    label: "CLOSE UP",
    secondary: "YPOS",
    variant: "dark",
    hasLed: true,
    factoryName: "Close Up",
    factorySecondaryName: "Y Position",
    description:
      "Creates a punch-in / close-up on the current clip. The secondary control adjusts vertical position.",
  },
  {
    id: "place-on-top",
    cluster: "edit",
    hid: 0x05,
    label: "PLACE ON TOP",
    variant: "dark",
    factoryName: "Place On Top",
    description: "Places the source clip on the track above the current timeline clip.",
  },
  {
    id: "src-owr",
    cluster: "edit",
    hid: 0x06,
    label: "SRC O/WR",
    variant: "dark",
    factoryName: "Source Overwrite",
    description: "Overwrites the timeline with the source clip without rippling other clips.",
  },
  {
    id: "esc",
    cluster: "utility",
    hid: 0x31,
    label: "ESC",
    secondary: "UNDO",
    variant: "dark",
    factoryName: "Escape",
    factorySecondaryName: "Undo",
    description: "Cancels the current tool or dialog. The secondary function undoes the last action.",
  },
  {
    id: "sync-bin",
    cluster: "utility",
    hid: 0x1f,
    label: "SYNC BIN",
    variant: "dark",
    factoryName: "Sync Bin",
    description: "Opens the sync bin used for multicam / synchronized clips.",
  },
  {
    id: "audio-level",
    cluster: "utility",
    hid: 0x2c,
    label: "AUDIO LEVEL",
    secondary: "MARK",
    variant: "dark",
    factoryName: "Audio Level",
    factorySecondaryName: "Mark",
    description: "Adjusts clip audio level. The secondary function sets a mark.",
  },
  {
    id: "full-view",
    cluster: "utility",
    hid: 0x2d,
    label: "FULL VIEW",
    secondary: "RVW",
    variant: "red",
    factoryName: "Full View",
    factorySecondaryName: "Review",
    description: "Toggles full-viewer mode. The secondary function starts review playback.",
  },
  {
    id: "trans",
    cluster: "utility",
    hid: 0x22,
    label: "TRANS",
    secondary: "TITLE",
    variant: "dark",
    hasLed: true,
    factoryName: "Transition",
    factorySecondaryName: "Title",
    description: "Adds or selects a transition. The secondary function works with titles.",
  },
  {
    id: "split",
    cluster: "utility",
    hid: 0x2f,
    label: "SPLIT",
    secondary: "MOVE",
    variant: "dark",
    factoryName: "Split",
    factorySecondaryName: "Move",
    description: "Splits the clip under the playhead into two clips.",
  },
  {
    id: "snap",
    cluster: "utility",
    hid: 0x2e,
    label: "SNAP",
    secondary: "=",
    variant: "dark",
    hasLed: true,
    factoryName: "Snap",
    factorySecondaryName: "Equals",
    description: "Turns timeline snapping on or off so clips jump to nearby edit points.",
  },
  {
    id: "ripl-del",
    cluster: "utility",
    hid: 0x2b,
    label: "RIPL DEL",
    variant: "dark",
    factoryName: "Ripple Delete",
    description: "Deletes the selected clip and closes the gap so later clips slide left.",
  },
  {
    id: "source",
    cluster: "transport",
    hid: 0x1a,
    label: "SOURCE",
    variant: "dark-wide",
    factoryName: "Source",
    description: "Sends the jog wheel and related keys to the source viewer.",
  },
  {
    id: "timeline",
    cluster: "transport",
    hid: 0x1b,
    label: "TIMELINE",
    variant: "dark-wide",
    factoryName: "Timeline",
    description: "Sends the jog wheel and related keys to the timeline.",
  },
  {
    id: "shtl",
    cluster: "modes",
    hid: 0x1c,
    label: "SHTL",
    variant: "white",
    hasLed: true,
    factoryName: "Shuttle",
    description:
      "Puts the wheel in Shuttle mode: turn it to play forward or reverse at a variable speed.",
  },
  {
    id: "jog",
    cluster: "modes",
    hid: 0x1d,
    label: "JOG",
    variant: "white",
    hasLed: true,
    factoryName: "Jog",
    description: "Puts the wheel in Jog mode: turn it to move one frame at a time.",
  },
  {
    id: "scrl",
    cluster: "modes",
    hid: 0x1e,
    label: "SCRL",
    variant: "white",
    hasLed: true,
    factoryName: "Scroll",
    description: "Puts the wheel in Scroll mode: turn it to move along the timeline.",
  },
  {
    id: "in",
    cluster: "marks",
    hid: 0x07,
    label: "IN",
    secondary: "CLR",
    variant: "white-wide",
    factoryName: "Mark In",
    factorySecondaryName: "Clear In",
    description: "Sets an In point. The secondary function clears the In point.",
  },
  {
    id: "out",
    cluster: "marks",
    hid: 0x08,
    label: "OUT",
    secondary: "CLR",
    variant: "white-wide",
    factoryName: "Mark Out",
    factorySecondaryName: "Clear Out",
    description: "Sets an Out point. The secondary function clears the Out point.",
  },
  {
    id: "trim-in",
    cluster: "trim",
    hid: 0x09,
    label: "TRIM IN",
    variant: "dark",
    factoryName: "Trim In",
    description: "Trims the In point of the clip under the playhead.",
  },
  {
    id: "trim-out",
    cluster: "trim",
    hid: 0x0a,
    label: "TRIM OUT",
    variant: "dark",
    factoryName: "Trim Out",
    description: "Trims the Out point of the clip under the playhead.",
  },
  {
    id: "roll",
    cluster: "trim",
    hid: 0x0b,
    label: "ROLL",
    secondary: "SLIDE",
    variant: "dark",
    factoryName: "Roll",
    factorySecondaryName: "Slide",
    description:
      "Rolls an edit point (moves the cut without changing total duration). Secondary is Slide.",
  },
  {
    id: "slip-src",
    cluster: "trim",
    hid: 0x0c,
    label: "SLIP SRC",
    variant: "dark",
    factoryName: "Slip Source",
    description: "Slips the source media used by a clip without moving the clip on the timeline.",
  },
  {
    id: "slip-dest",
    cluster: "trim",
    hid: 0x0d,
    label: "SLIP DEST",
    variant: "dark",
    factoryName: "Slip Destination",
    description: "Slips the clip on the timeline while keeping its in/out duration.",
  },
  {
    id: "trans-dur",
    cluster: "trim",
    hid: 0x0e,
    label: "TRANS DUR",
    secondary: "SET",
    variant: "dark",
    factoryName: "Transition Duration",
    factorySecondaryName: "Set",
    description: "Sets how long a transition lasts. Secondary confirms / sets the value.",
  },
  {
    id: "cut",
    cluster: "trim",
    hid: 0x0f,
    label: "CUT",
    variant: "dark",
    hasLed: true,
    factoryName: "Cut",
    description: "Applies a cut (hard cut) as the transition type.",
  },
  {
    id: "dis",
    cluster: "trim",
    hid: 0x10,
    label: "DIS",
    variant: "dark",
    hasLed: true,
    factoryName: "Dissolve",
    description: "Applies a dissolve / cross-fade transition.",
  },
  {
    id: "smth-cut",
    cluster: "trim",
    hid: 0x11,
    label: "SMTH CUT",
    variant: "dark",
    hasLed: true,
    factoryName: "Smooth Cut",
    description: "Applies DaVinci Resolve’s Smooth Cut transition.",
  },
  {
    id: "cam7",
    cluster: "multicam",
    hid: 0x39,
    label: "CAM 7",
    variant: "dark",
    hasLed: true,
    factoryName: "Camera 7",
    description: "Cuts to camera 7 in a multicam clip.",
  },
  {
    id: "cam8",
    cluster: "multicam",
    hid: 0x3a,
    label: "CAM 8",
    variant: "dark",
    hasLed: true,
    factoryName: "Camera 8",
    description: "Cuts to camera 8 in a multicam clip.",
  },
  {
    id: "cam9",
    cluster: "multicam",
    hid: 0x3b,
    label: "CAM 9",
    variant: "dark",
    hasLed: true,
    factoryName: "Camera 9",
    description: "Cuts to camera 9 in a multicam clip.",
  },
  {
    id: "live-owr",
    cluster: "multicam",
    hid: 0x30,
    label: "LIVE O/WR",
    secondary: "RND",
    variant: "dark",
    hasLed: true,
    factoryName: "Live Overwrite",
    factorySecondaryName: "Random",
    description: "Live overwrite while switching cameras. Secondary picks a random camera.",
  },
  {
    id: "cam4",
    cluster: "multicam",
    hid: 0x36,
    label: "CAM 4",
    variant: "dark",
    hasLed: true,
    factoryName: "Camera 4",
    description: "Cuts to camera 4 in a multicam clip.",
  },
  {
    id: "cam5",
    cluster: "multicam",
    hid: 0x37,
    label: "CAM 5",
    variant: "dark",
    hasLed: true,
    factoryName: "Camera 5",
    description: "Cuts to camera 5 in a multicam clip.",
  },
  {
    id: "cam6",
    cluster: "multicam",
    hid: 0x38,
    label: "CAM 6",
    variant: "dark",
    hasLed: true,
    factoryName: "Camera 6",
    description: "Cuts to camera 6 in a multicam clip.",
  },
  {
    id: "video-only",
    cluster: "multicam",
    hid: 0x25,
    label: "VIDEO ONLY",
    variant: "dark",
    hasLed: true,
    factoryName: "Video Only",
    description: "Makes the next edit change video only, leaving audio as it is.",
  },
  {
    id: "cam1",
    cluster: "multicam",
    hid: 0x33,
    label: "CAM 1",
    variant: "dark",
    hasLed: true,
    factoryName: "Camera 1",
    description: "Cuts to camera 1 in a multicam clip.",
  },
  {
    id: "cam2",
    cluster: "multicam",
    hid: 0x34,
    label: "CAM 2",
    variant: "dark",
    hasLed: true,
    factoryName: "Camera 2",
    description: "Cuts to camera 2 in a multicam clip.",
  },
  {
    id: "cam3",
    cluster: "multicam",
    hid: 0x35,
    label: "CAM 3",
    variant: "dark",
    hasLed: true,
    factoryName: "Camera 3",
    description: "Cuts to camera 3 in a multicam clip.",
  },
  {
    id: "audio-only",
    cluster: "multicam",
    hid: 0x26,
    label: "AUDIO ONLY",
    variant: "dark",
    hasLed: true,
    factoryName: "Audio Only",
    description: "Makes the next edit change audio only, leaving video as it is.",
  },
  {
    id: "stop-play",
    cluster: "multicam",
    hid: 0x3c,
    label: "STOP/PLAY",
    variant: "play",
    factoryName: "Stop / Play",
    description: "Starts or stops playback.",
  },
  {
    id: "jog-wheel",
    cluster: "wheel",
    hid: null,
    kind: "wheel",
    label: "JOG WHEEL",
    variant: "wheel",
    factoryName: "Jog Wheel",
    description:
      "The large dial. In Jog it moves frame by frame, in Shuttle it shuttles playback, and in Scroll it moves the timeline.",
  },
];

const BUTTON_BY_ID = Object.fromEntries(SPEED_EDITOR_BUTTONS.map((button) => [button.id, button]));
